export const LANGUAGE_OPTIONS = [
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "Go",
    "Ruby",
    "Swift",
    "PHP",
    "Kotlin",
    "Rust",
    "TypeScript",
    "R",
    "Perl",
    "Scala"
]

export const MOCK_DATA = {
    "language": "kotlin",
    "words": [
        "Gradle",
        "JetBrains",
        "JVM",
        "Lambdas",
        "Concurrency",
        "IntelliJ IDEA",
        "Data Science",
        "Kotlin Native",
        "Android Studio",
        "Kotlin Multiplatform",
        "Null Safety",
        "Object-Oriented",
        "Spring Boot",
        "Microservices",
        "Server-side Development",
        "Spring Framework",
        "Maven",
        "WebAssembly",
        "Kotlin/JS",
        "API Development",
        "Kotlin Scripting",
        "Extension Functions",
        "Interoperability",
        "Higher-Order Functions",
        "Flow",
        "Ktor",
        "JavaScript",
        "iOS",
        "Reactive Programming",
        "Android",
        "Delegated Properties",
        "Data Classes",
        "Kotlin Ecosystem",
        "Kotlin",
        "Kotlin/Native",
        "KotlinConf",
        "Coroutines",
        "Kotlin DSL",
        "Kotlin Community",
        "Smart Casts",
        "Functional",
        "Kotlinx.coroutines",
        "Machine Learning",
        "Kotlin Playground",
        "Sealed Classes",
        "Java",
        "Type Inference"
    ]
}

export const VALUES_TIME = [ { value: 3 }, { value: 15 }, { value: 30 }, { value: 45 }, { value: 60 } ]